6631022: PackageManager.init() eats ClassNotFoundException
I removed the try/catch from the generated PackageManager.init() and tested by doing a CVM_PRELOAD_LIB=false CVM_STATICLINK_LIBS=true build, removing lib/jsr75.jar, and starting up the vm. It properly exited with the following:

java.lang.ClassNotFoundException: com.sun.cdc.config.jsr75.Initializer
	at java.lang.ClassLoader.loadBootstrapClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at com.sun.cdc.config.PackageManager.init(Unknown Source)
	at java.lang.System.initializeSystemClass(Unknown Source)
Cannot start VM (error during System.initializeSystemClass())
Could not create JVM

I also fixed the PackageManger.java dependencies so it rebuilds when the .xml or .xsl file changes.

Reviewed by Roman and Steve